[workspace]
members = ["daemon"]
exclude = [
  "bones/core/bus",
  "bones/core/contract",
  "bones/core/logging",
  "bones/core/runner",
  "bones/core/wasm-extensions",
  "bones/shared/bones-messages",
  "bones/vendor/pubsub-bus",
]
resolver = "2"

[workspace.package]
version = "0.3.1"
edition = "2021"
license = "MIT"
authors = ["Copper Contributors"]
